type: Test
spec:
  id: uqLD2XHSg
  name: Product Recommendation
  description: Should get the products recommendation
  trigger:
    type: http
    httpRequest:
      method: GET
      url: http://otel-demo-frontend.otel-demo.svc.cluster.local:8080/api/recommendations
      headers:
      - key: Content-Type
        value: application/json
  specs:
  - selector: span[tracetest.span.type="general" name="Tracetest trigger"]
    name: Test trigger should receive a success response from frontend
    assertions:
    - attr:tracetest.response.status  =  200
  - selector: span[tracetest.span.type="rpc" name="/oteldemo.RecommendationService/ListRecommendations" rpc.system="grpc" rpc.method="ListRecommendations" rpc.service="oteldemo.RecommendationService"]
    name: RecomendationService/ListRecommendations should be called via gRPC and return recommend 5 products
    assertions:
    - attr:app.products_recommended.count  =  5
    - attr:rpc.grpc.status_code  =  0
  - selector: span[tracetest.span.type="rpc" name="oteldemo.ProductCatalogService/GetProduct" rpc.system="grpc" rpc.method="GetProduct" rpc.service="oteldemo.ProductCatalogService"]
    name: ProductCatalogService/GetProduct should be called via gRPC 4 times by the frontend
    assertions:
    - attr:tracetest.selected_spans.count  =  4
    - attr:rpc.grpc.status_code  =  0
  - selector: span[tracetest.span.type="rpc" name="oteldemo.ProductCatalogService/ListProducts" rpc.system="grpc" rpc.method="ListProducts" rpc.service="oteldemo.ProductCatalogService"]
    name: ProductCatalogService/ListProducts should be called via gRPC and return 10 products
    assertions:
    - attr:app.products.count = 10
    - attr:rpc.grpc.status_code = 0
